### ISSUE TITLE
Assembly jar file error - No functional server found

### ISSUE THREAD

**Issue by Wei-1** [alibaltschun/test-shade-sbt-spark-scala#1]
After `sbt assembly` and get the jar file.

By submitting the job to Spark
`spark-submit --master local[2] --class HelloWorldServer target/scala-2.11/test-shade-sbt-spark-scala-assembly-0.1-SNAPSHOT.jar`

we will get this error:

```
Exception in thread "main" io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact
	at io.grpc.ServerProvider.provider(ServerProvider.java:55)
	at io.grpc.ServerBuilder.forPort(ServerBuilder.java:39)
	at HelloWorldServer.HelloWorldServer$$start(main.scala:49)
	at HelloWorldServer$.main(main.scala:15)
	at HelloWorldServer.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2018-08-21 16:53:32 INFO  ShutdownHookManager:54 - Shutdown hook called
```

**Comment by alibaltschun** [comment]
this repo was out of date, coz the real project on private repo.

try to change `import io.grpc.{Server, ServerBuilder}` to
`import io.grpc.Server`
`import io.grpc.netty.NettyServerBuilderr`

and change `serverBuilder` in main code to `NettyServerBuilder.`

**Comment by Wei-1** [comment]
The server can be started without error by changing to `NettyServerBuilder`. Thanks!
